# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20161226_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
